#!/bin/bash

is_tmux() {
  if [ -n "$TMUX" ]; then
    true
  else
    false
  fi
}

if is_tmux; then
  fzf="fzf-tmux -p --color=16"
else
  fzf="fzf --color=16"
fi

if [ "$1" == "--normal" ]; then
  fzf="fzf --color=16"
fi
