#!/bin/bash

source $HOME/.config/tsn/scripts/tmux/menu/lib/global
source $HOME/.config/tsn/scripts/aliases

selection=$(for key in "${!cfglist[@]}"
  do
    echo "$key ${cfglist[$key]}"
  done | $fzf
)

file=$(echo $selection | cut -d ' ' -f2)
location=$(echo $file | rev | cut -d '/' -f2- | rev)

if [ -n "$file" ]; then
  if is_tmux; then
    tmux new-window "cd $location; nvim $file"
  else
    cd $location; nvim $file
  fi
fi
