#!/bin/bash

source $HOME/.config/tsn/scripts/tmux/menu/lib/global

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# FILE="emojijson" # from https://github.com/amio/emoji.json
FILE="emojilist" # from https://git.io/JXXO7

if [ "$FILE" == "emojijson" ]; then
  lines=`jq -r '.[] | [.char, .name] | join("=")' $SCRIPT_DIR/../lib/emojijson`
elif [ "$FILE" == "emojilist" ]; then
  lines=`cat $SCRIPT_DIR/../lib/emojilist`
fi

set -f              # turn off globbing
IFS='
'                   # split at newlines only

selection=$(printf '%s\n' ${lines[@]} | if [ -n "$TMUX" ]; then fzf-tmux -p; else fzf; fi )

# unset IFS
# set +f

if [ -n "$selection" ]; then
  if [ "$FILE" == "emojijson" ]; then
    echo "$selection" | cut -d '=' -f1 | xclip -selection clipboard
  elif [ "$FILE" == "emojilist" ]; then
    echo "$selection" | cut -d ' ' -f1 | xclip -selection clipboard
  fi
fi

