#!/bin/bash

source $HOME/.config/tsn/scripts/tmux/menu/lib/global

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# FILE="emojijson" # from https://github.com/amio/emoji.json
FILE="emojilist" # from https://git.io/JXXO7

if [ "$FILE" == "emojijson" ]; then
  lines=`jq -r '.[] | [.char, .name] | join("=")' $SCRIPT_DIR/../lib/emojijson`
elif [ "$FILE" == "emojilist" ]; then
  lines=`cat $SCRIPT_DIR/../lib/emojilist`
fi

selection=$(for emoji in "$lines"
  do
    echo "$emoji"
  done | $fzf
)

if [ -n "$selection" ]; then
  if [ "$FILE" == "emojijson" ]; then
    emoji=$(echo -n "$selection" | cut -d '=' -f1)
    echo -n $emoji | xclip -selection clipboard
  elif [ "$FILE" == "emojilist" ]; then
    emoji=$(echo -n "$selection" | cut -d ' ' -f1)
    echo -n $emoji | xclip -selection clipboard
  fi
fi
