#!/bin/bash

source $HOME/.config/tsn/scripts/tmux/menu/lib/global

location=`
for i in "$(ls -d ~/Projects/*/*/)"; do
  echo "$i" 
done | $fzf`

if is_tmux; then
  tmux new-window "cd $location; nvim"
else
  cd $location; nvim
fi
